/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomePage_Package;

import DbConnection.DatabaseConn;
import java.sql.Connection;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Roshli
 */
public class ReportFrame extends javax.swing.JFrame {
    
    Connection con = null;

    /**
     * Creates new form ReportFrame
     */
    public ReportFrame() {
        initComponents();
        //initComponents();
        
        con = DatabaseConn.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Commission = new javax.swing.JButton();
        Salary = new javax.swing.JButton();
        Laon = new javax.swing.JButton();
        BlackList = new javax.swing.JButton();
        Customer = new javax.swing.JButton();
        Supplier = new javax.swing.JButton();
        Reorder_Stock = new javax.swing.JButton();
        Master_Item = new javax.swing.JButton();
        Loyalty = new javax.swing.JButton();
        Transactions = new javax.swing.JButton();
        Item = new javax.swing.JButton();
        Services = new javax.swing.JButton();
        Emp_Details = new javax.swing.JButton();
        Invoice2pay = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        LeaveReq = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Commission.setText("Commission");
        Commission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommissionActionPerformed(evt);
            }
        });

        Salary.setText("Salary");
        Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryActionPerformed(evt);
            }
        });

        Laon.setText("Loan");
        Laon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaonActionPerformed(evt);
            }
        });

        BlackList.setText("BlackList");
        BlackList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackListActionPerformed(evt);
            }
        });

        Customer.setText("Customer");
        Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerActionPerformed(evt);
            }
        });

        Supplier.setText("Supplier");
        Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierActionPerformed(evt);
            }
        });

        Reorder_Stock.setText("Reorder Stock");
        Reorder_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reorder_StockActionPerformed(evt);
            }
        });

        Master_Item.setText("Master Item");
        Master_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Master_ItemActionPerformed(evt);
            }
        });

        Loyalty.setText("Loyalty");
        Loyalty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoyaltyActionPerformed(evt);
            }
        });

        Transactions.setText("Transactions");
        Transactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionsActionPerformed(evt);
            }
        });

        Item.setText("Items");
        Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemActionPerformed(evt);
            }
        });

        Services.setText("Services");
        Services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServicesActionPerformed(evt);
            }
        });

        Emp_Details.setText("Employee Details");
        Emp_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emp_DetailsActionPerformed(evt);
            }
        });

        Invoice2pay.setText("Invoict2pay");
        Invoice2pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Invoice2payActionPerformed(evt);
            }
        });

        jButton15.setText("BateryCom");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("TodaysOrders");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("Order");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        LeaveReq.setText("Leave Requests");
        LeaveReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveReqActionPerformed(evt);
            }
        });

        jButton19.setText("jButton1");

        jButton20.setText("JobsDone");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("JobDate");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setText("ServComplain");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("TyreCom");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Master_Item)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Reorder_Stock)
                .addGap(18, 18, 18)
                .addComponent(Supplier)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Services)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Emp_Details))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Laon)
                        .addGap(18, 18, 18)
                        .addComponent(Salary)
                        .addGap(18, 18, 18)
                        .addComponent(Commission)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Customer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BlackList)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton23)
                                .addGap(18, 18, 18)
                                .addComponent(jButton22)
                                .addGap(18, 18, 18)
                                .addComponent(jButton21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton20)
                                .addGap(18, 18, 18)
                                .addComponent(jButton19))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(404, 404, 404)
                                .addComponent(jButton15))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Loyalty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Transactions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Item)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LeaveReq)
                .addGap(18, 18, 18)
                .addComponent(jButton17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Invoice2pay)
                        .addGap(108, 108, 108))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Laon)
                            .addComponent(Salary)
                            .addComponent(Commission)
                            .addComponent(Customer)
                            .addComponent(BlackList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Master_Item)
                            .addComponent(Reorder_Stock)
                            .addComponent(Supplier))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Item)
                                    .addComponent(Transactions)
                                    .addComponent(Loyalty)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Emp_Details)
                                    .addComponent(Services))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LeaveReq)
                            .addComponent(jButton17)
                            .addComponent(Invoice2pay)))
                    .addComponent(jButton16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton23)
                    .addComponent(jButton22)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20)
                    .addComponent(jButton19))
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\pushpithtaComTyre.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "SELECT ci.complaint_id, ci.customer_name, ci.complaint_type,ci.claim_type, ci.item_type, ct.item_id, ct.date_of_sale, ct.sold_price, ct.serial_no,pt.amount, pt.date, pt.invoice_no,rt.tax_amount, rt.refund_date,rt.invoice_no,rt.refund_amount\n" +
"FROM complaint_item ci, complaint_tyre ct, payment_tyre pt, refund_tyre rt";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void LaonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaonActionPerformed
                                     
         try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\Sandaru_loan.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "Select * from fulloan";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_LaonActionPerformed

    private void SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\Sandaru_Salary.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "Select employeeID,month,Salary from finalsaldet";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_SalaryActionPerformed

    private void CommissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommissionActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\Sandaru_Commision.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "Select employeeID,sum(Commission_Amount) as Commision_Amount from commision group by employeeID";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_CommissionActionPerformed

    private void Master_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Master_ItemActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\Roshli_Master_Item.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "Select * From category";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_Master_ItemActionPerformed

    private void Reorder_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reorder_StockActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\Reorder_Roshli.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "SELECT c.CatCode AS 'Category Name',COUNT(i.CatCode) AS 'Stock In Hand' FROM category c, item i WHERE i.CatCode = c.CatCode AND c.ReorderLevel >= (SELECT count(*) FROM item WHERE CatCode = c.CatCode) GROUP BY c.CatCode ";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_Reorder_StockActionPerformed

    private void SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\Dhanushi_Supplier.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "Select * from supplier1";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_SupplierActionPerformed

    private void CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\DanushiCustomer.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "Select * from customer";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_CustomerActionPerformed

    private void BlackListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackListActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\Danushi_BlackList.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "Select * from customer1";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_BlackListActionPerformed

    private void LoyaltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoyaltyActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\Danushi_Loyalty.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "Select * from loyaltyscheme";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_LoyaltyActionPerformed

    private void TransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionsActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\Navodya_Trans.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "SELECT CustomerID, count(TransID) AS 'Number of transactions', sum(Amount) AS 'Total Amount' From stransaction GROUP BY CustomerID";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_TransactionsActionPerformed

    private void ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\NavodyaServices.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "SELECT * FROM sitem ";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_ItemActionPerformed

    private void ServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServicesActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\NavodyaOriService.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "SELECT * FROM sservice ";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_ServicesActionPerformed

    private void Emp_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emp_DetailsActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\TeshanEmpDetails.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "SELECT * FROM emp_details";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_Emp_DetailsActionPerformed
 
    private void LeaveReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveReqActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\Teshan Leave.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "SELECT * FROM leave_request";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_LeaveReqActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\ImashaOrdes.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "SELECT order.ordernumber,order.supid,order.serialno,order.quantity,order.dateneeded,order.type,order.manufacturer,order.date FROM `order` left join `invoice` on order.ordernumber=invoice.ordernum WHERE invoice.ordernum IS NULL";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\ImashaTodayOrder.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "SELECT `ordernumber`, `supid`, `serialno`, `quantity`, `type`, `manufacturer`, `dateneeded`FROM `order` where order.date<CURDATE() and order.invreseiveandpaid='false'";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    
    }//GEN-LAST:event_jButton16ActionPerformed

    private void Invoice2payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Invoice2payActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\ImashaOrdersMade.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "SELECT invoice.invoicenumber, invoice.ordernum, invoice.supid, sum(invoice.tottalprice) as Totalprice FROM `invoice` left join `order` on invoice.ordernum = manojtyre.order.ordernumber WHERE manojtyre.order.ordernumber IS NOT NULL group by manojtyre.order.ordernumber, invoice.invoicenumber ";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_Invoice2payActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\PushpithaReorort1.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "SELECT cb.complaint_id,cb.item_id,cb.sold_price,cb.dateof_sale, cb.serial_no,ci.complaint_date, ci.customer_name, ci.complaint_type, ci.item_type, pb.amount, pb.invoice_no, pr.battery_type,pr.special_price,pr.price, pr.discount_percentage FROM complaint_battery cb, complaint_item ci, payment_battery pb,prorata_battery pr";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\PushpithaServCom.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "SELECT cs.complaint_id, cs.job_no, cs.cusname,ws.final_cost, ws.discount\n" +
"FROM complaint_service cs, warranty_claim_service ws";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\RavinduR1.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "SELECT job_type , COUNT(jid) FROM final_job_table group by job_type";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        try {
            String ResReport = "C:\\Users\\Roshli\\Documents\\NetBeansProjects\\manoj_tyre\\src\\Report\\RavinduR2.jrxml";
            JasperDesign jd = JRXmlLoader.load(ResReport);
            String sql = "select jid as 'job ID',cusID as 'cusID', name as 'cus_name', reg_no as 'regNo', v_type as 'vehicle',job_type as 'job',eid as 'EmpId' ,st_hh as 'startHr', st_mm as 'startMn',st_am_pm as 'am/pm' ,fin_hh as 'FinHr', fin_mm as 'FinMn',fin_am_pm as 'am/pm'  from final_job_table";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport  jrs = JasperCompileManager.compileReport(jd);
            JasperPrint jps = JasperFillManager.fillReport(jrs, null,con);
            JasperViewer.viewReport(jps,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BlackList;
    private javax.swing.JButton Commission;
    private javax.swing.JButton Customer;
    private javax.swing.JButton Emp_Details;
    private javax.swing.JButton Invoice2pay;
    private javax.swing.JButton Item;
    private javax.swing.JButton Laon;
    private javax.swing.JButton LeaveReq;
    private javax.swing.JButton Loyalty;
    private javax.swing.JButton Master_Item;
    private javax.swing.JButton Reorder_Stock;
    private javax.swing.JButton Salary;
    private javax.swing.JButton Services;
    private javax.swing.JButton Supplier;
    private javax.swing.JButton Transactions;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    // End of variables declaration//GEN-END:variables
}
