/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package HomePage_Package;
import Manage_Customer_Supplier_Package.*;
import RetailSalesHandling_Package.*;
import Inventory_mng.*;
import DbConnection.*;
import HomePage_Package.*;
import Inventory_mng.*;
import JobMng_Package.*;
import Manage_Customer_Supplier_Package.*;
import RetailSalesHandling_Package.*;
import payrollPACKAGE.*;
import PurchasingPackage.*;
import ComplaintMng_Package.*;
import Employee_AttendanceMng_Package.*;
import AppPackage.AnimationClass;
import ComplaintMng_Package.*;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.*;

/**
 *
 * @author Teshan Chathushka
 */
public class UserHome extends javax.swing.JFrame {

    /**
     * Creates new form TestHome
     */
    int xMouse;//xMouse Global
    int yMouse;//yMouse Global
    int timeRun=0;
    public UserHome() {
        initComponents();
        setIcon();
        setLocationRelativeTo(null);
        setMenuHide();
        new Thread(){
            public void run(){
                while(timeRun==0)
                {
                    Calendar cal = new GregorianCalendar();
                    
                    int hour=cal.get(Calendar.HOUR);
                    int min=cal.get(Calendar.MINUTE);
                    int sec=cal.get(Calendar.SECOND);
                    int am_pm=cal.get(Calendar.AM_PM);
                    
                    String DayNight="";
                    if(am_pm==1){
                        DayNight="PM";
                    }
                    else{
                        DayNight="AM";
                    }
                    String time =hour+":"+min/*+":"+sec*/;
                    String day_night = DayNight;
                    Clock.setText(time);
                    Am_Pm.setText(day_night);
                }
            }
        }.start();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MMM-dd");
                 String date=sdf.format(new Date());
                 dateLable.setText(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubPanel = new javax.swing.JPanel();
        Info = new javax.swing.JLabel();
        Other_login_sign = new javax.swing.JLabel();
        TitleBar = new javax.swing.JPanel();
        logUserImg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Minimize = new javax.swing.JLabel();
        Cancel = new javax.swing.JLabel();
        Uname_Separator = new javax.swing.JSeparator();
        signOut_button = new javax.swing.JLabel();
        Show_Uname = new javax.swing.JLabel();
        DetailPanal = new javax.swing.JPanel();
        TimeLine = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        Clock = new javax.swing.JLabel();
        Am_Pm = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        Main_menu_LayeredPane = new javax.swing.JLayeredPane();
        User_menu_panel = new javax.swing.JPanel();
        Inventory_icon1 = new javax.swing.JLabel();
        Inventory_txt1 = new javax.swing.JLabel();
        Inventory_back1 = new javax.swing.JLabel();
        Item_icon1 = new javax.swing.JLabel();
        Item_txt1 = new javax.swing.JLabel();
        Item_back1 = new javax.swing.JLabel();
        Sales_Icon1 = new javax.swing.JLabel();
        Sales_txt1 = new javax.swing.JLabel();
        Sales_back1 = new javax.swing.JLabel();
        Claims_Icon1 = new javax.swing.JLabel();
        Claims_txt1 = new javax.swing.JLabel();
        Claims_back1 = new javax.swing.JLabel();
        Employees_Icon1 = new javax.swing.JLabel();
        Employees_txt1 = new javax.swing.JLabel();
        Employees_back1 = new javax.swing.JLabel();
        Customers_Icon1 = new javax.swing.JLabel();
        Customers_txt1 = new javax.swing.JLabel();
        Customers_txt2 = new javax.swing.JLabel();
        Customers_back1 = new javax.swing.JLabel();
        Jobs_Icon1 = new javax.swing.JLabel();
        Jobs_txt1 = new javax.swing.JLabel();
        Jobs_back1 = new javax.swing.JLabel();
        ManageEmployee_subMenu_panel1 = new javax.swing.JPanel();
        manage_employee_close2 = new javax.swing.JLabel();
        Emp_salaryMng_Icon1 = new javax.swing.JLabel();
        EmpSalaryMng_txt3 = new javax.swing.JLabel();
        EmpSalaryMng_txt4 = new javax.swing.JLabel();
        Emp_salaryMng_back1 = new javax.swing.JLabel();
        Emp_atendance_Icon1 = new javax.swing.JLabel();
        Emp_attendance_txt3 = new javax.swing.JLabel();
        Emp_attendance_txt4 = new javax.swing.JLabel();
        Emp_atendance_back1 = new javax.swing.JLabel();
        Manage_employee_back2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubPanel.setBackground(new java.awt.Color(37, 4, 70));
        SubPanel.setPreferredSize(new java.awt.Dimension(42, 470));

        Info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Info-32.png"))); // NOI18N
        Info.setToolTipText("System Information");
        Info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InfoMouseExited(evt);
            }
        });
        Info.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                InfoMouseMoved(evt);
            }
        });

        Other_login_sign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Final State-32.png"))); // NOI18N
        Other_login_sign.setToolTipText("Other User is loged");
        Other_login_sign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Other_login_signMouseExited(evt);
            }
        });
        Other_login_sign.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Other_login_signMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout SubPanelLayout = new javax.swing.GroupLayout(SubPanel);
        SubPanel.setLayout(SubPanelLayout);
        SubPanelLayout.setHorizontalGroup(
            SubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Info, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Other_login_sign, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        SubPanelLayout.setVerticalGroup(
            SubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Other_login_sign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 614, Short.MAX_VALUE)
                .addComponent(Info)
                .addContainerGap())
        );

        getContentPane().add(SubPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 700));

        TitleBar.setBackground(new java.awt.Color(255, 255, 255));
        TitleBar.setPreferredSize(new java.awt.Dimension(1110, 52));
        TitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TitleBarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TitleBarMousePressed(evt);
            }
        });
        TitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TitleBarMouseDragged(evt);
            }
        });
        TitleBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logUserImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Male User-32 (dark).png"))); // NOI18N
        logUserImg.setToolTipText("User Info");
        logUserImg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logUserImgMouseMoved(evt);
            }
        });
        logUserImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logUserImgMouseExited(evt);
            }
        });
        TitleBar.add(logUserImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        TitleBar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Minimize Window-32 (1).png"))); // NOI18N
        Minimize.setToolTipText("Minimise");
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeMouseExited(evt);
            }
        });
        Minimize.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MinimizeMouseMoved(evt);
            }
        });
        TitleBar.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, 30));

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Cancel-32.png"))); // NOI18N
        Cancel.setToolTipText("Close");
        Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelMouseExited(evt);
            }
        });
        Cancel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CancelMouseMoved(evt);
            }
        });
        TitleBar.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, 30));
        TitleBar.add(Uname_Separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 70, 10));

        signOut_button.setBackground(new java.awt.Color(204, 204, 204));
        signOut_button.setForeground(new java.awt.Color(51, 0, 0));
        signOut_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signOut_button.setText("SignOut");
        signOut_button.setToolTipText("SignOut");
        signOut_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOut_button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                signOut_buttonMouseMoved(evt);
            }
        });
        signOut_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signOut_buttonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signOut_buttonMouseExited(evt);
            }
        });
        TitleBar.add(signOut_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 70, 40));

        Show_Uname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Show_Uname.setText("Normal User");
        Show_Uname.setToolTipText("User Type");
        TitleBar.add(Show_Uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 40));

        getContentPane().add(TitleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1110, -1));

        DetailPanal.setBackground(new java.awt.Color(84, 8, 159));
        DetailPanal.setPreferredSize(new java.awt.Dimension(1110, 550));
        DetailPanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TimeLine.setBackground(new java.awt.Color(204, 204, 204));
        TimeLine.setPreferredSize(new java.awt.Dimension(1110, 120));
        TimeLine.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SLogo.png"))); // NOI18N
        TimeLine.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 120));

        Clock.setFont(new java.awt.Font("Digital-7 Mono", 0, 48)); // NOI18N
        Clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clock.setText("00:00");
        Clock.setToolTipText("Clock");
        TimeLine.add(Clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 11, 128, 53));

        Am_Pm.setFont(new java.awt.Font("Digital-7 Mono", 0, 24)); // NOI18N
        Am_Pm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Am_Pm.setToolTipText("Clock");
        TimeLine.add(Am_Pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1045, 21, 26, 43));

        dateLable.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        dateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLable.setText("00 00 0000");
        TimeLine.add(dateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 70, 212, 38));

        DetailPanal.add(TimeLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Main_menu_LayeredPane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Main_menu_LayeredPaneMouseMoved(evt);
            }
        });

        User_menu_panel.setBackground(new java.awt.Color(168, 125, 211));
        User_menu_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inventory_icon1.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        Inventory_icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inventory_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Inventory3.png"))); // NOI18N
        Inventory_icon1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Inventory_icon1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Inventory_icon1MouseMoved(evt);
            }
        });
        Inventory_icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_icon1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Inventory_icon1MouseExited(evt);
            }
        });
        User_menu_panel.add(Inventory_icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 55, 175, 170));

        Inventory_txt1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Inventory_txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inventory_txt1.setText("Inventory Handle");
        User_menu_panel.add(Inventory_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 140, 30));

        Inventory_back1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inventory_back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transperat.png"))); // NOI18N
        User_menu_panel.add(Inventory_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        Item_icon1.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        Item_icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/purchesing2.png"))); // NOI18N
        Item_icon1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Item_icon1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Item_icon1MouseMoved(evt);
            }
        });
        Item_icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Item_icon1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Item_icon1MouseExited(evt);
            }
        });
        User_menu_panel.add(Item_icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 55, 175, 170));

        Item_txt1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Item_txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item_txt1.setText("Item Purchasing");
        User_menu_panel.add(Item_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 140, 30));

        Item_back1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item_back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transperat.png"))); // NOI18N
        User_menu_panel.add(Item_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        Sales_Icon1.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        Sales_Icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sales_Icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sales.png"))); // NOI18N
        Sales_Icon1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Sales_Icon1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Sales_Icon1MouseMoved(evt);
            }
        });
        Sales_Icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sales_Icon1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Sales_Icon1MouseExited(evt);
            }
        });
        User_menu_panel.add(Sales_Icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 55, 175, 170));

        Sales_txt1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Sales_txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sales_txt1.setText("Manage Sales");
        User_menu_panel.add(Sales_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 140, 30));

        Sales_back1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sales_back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transperat.png"))); // NOI18N
        User_menu_panel.add(Sales_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        Claims_Icon1.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        Claims_Icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Claims_Icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/claims.png"))); // NOI18N
        Claims_Icon1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Claims_Icon1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Claims_Icon1MouseMoved(evt);
            }
        });
        Claims_Icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Claims_Icon1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Claims_Icon1MouseExited(evt);
            }
        });
        User_menu_panel.add(Claims_Icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 55, 175, 170));

        Claims_txt1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Claims_txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Claims_txt1.setText("Manage Claims");
        User_menu_panel.add(Claims_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 140, 30));

        Claims_back1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Claims_back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transperat.png"))); // NOI18N
        User_menu_panel.add(Claims_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, -1, -1));

        Employees_Icon1.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        Employees_Icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employees_Icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Employees.png"))); // NOI18N
        Employees_Icon1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Employees_Icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Employees_Icon1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Employees_Icon1MouseExited(evt);
            }
        });
        Employees_Icon1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Employees_Icon1MouseMoved(evt);
            }
        });
        User_menu_panel.add(Employees_Icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 295, 175, 170));

        Employees_txt1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Employees_txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employees_txt1.setText("Manage Employees");
        User_menu_panel.add(Employees_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 140, 30));

        Employees_back1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employees_back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transperat.png"))); // NOI18N
        User_menu_panel.add(Employees_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        Customers_Icon1.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        Customers_Icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Customers_Icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Customers.png"))); // NOI18N
        Customers_Icon1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Customers_Icon1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Customers_Icon1MouseMoved(evt);
            }
        });
        Customers_Icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Customers_Icon1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Customers_Icon1MouseExited(evt);
            }
        });
        User_menu_panel.add(Customers_Icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 295, 175, 170));

        Customers_txt1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Customers_txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Customers_txt1.setText("Manage Customers &");
        User_menu_panel.add(Customers_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 140, 30));

        Customers_txt2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Customers_txt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Customers_txt2.setText("Suppliers");
        User_menu_panel.add(Customers_txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 140, 20));

        Customers_back1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Customers_back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transperat.png"))); // NOI18N
        User_menu_panel.add(Customers_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        Jobs_Icon1.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        Jobs_Icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jobs_Icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Suplier.png"))); // NOI18N
        Jobs_Icon1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Jobs_Icon1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Jobs_Icon1MouseMoved(evt);
            }
        });
        Jobs_Icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jobs_Icon1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jobs_Icon1MouseExited(evt);
            }
        });
        User_menu_panel.add(Jobs_Icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 295, 175, 170));

        Jobs_txt1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Jobs_txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jobs_txt1.setText("Manage Jobs");
        User_menu_panel.add(Jobs_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 140, 30));

        Jobs_back1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jobs_back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transperat.png"))); // NOI18N
        User_menu_panel.add(Jobs_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        Main_menu_LayeredPane.add(User_menu_panel);
        User_menu_panel.setBounds(0, 0, 1110, 530);

        ManageEmployee_subMenu_panel1.setBackground(new java.awt.Color(168, 125, 211));
        ManageEmployee_subMenu_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manage_employee_close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-CancelWhite-32.png"))); // NOI18N
        manage_employee_close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manage_employee_close2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manage_employee_close2MouseExited(evt);
            }
        });
        manage_employee_close2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                manage_employee_close2MouseMoved(evt);
            }
        });
        ManageEmployee_subMenu_panel1.add(manage_employee_close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 130, -1, 32));

        Emp_salaryMng_Icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Emp_salaryMng_Icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SalaryMng.png"))); // NOI18N
        Emp_salaryMng_Icon1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Emp_salaryMng_Icon1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Emp_salaryMng_Icon1MouseMoved(evt);
            }
        });
        Emp_salaryMng_Icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Emp_salaryMng_Icon1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Emp_salaryMng_Icon1MouseExited(evt);
            }
        });
        ManageEmployee_subMenu_panel1.add(Emp_salaryMng_Icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 167, 175, 170));

        EmpSalaryMng_txt3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EmpSalaryMng_txt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmpSalaryMng_txt3.setText("Employee Salary");
        ManageEmployee_subMenu_panel1.add(EmpSalaryMng_txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 284, 140, 20));

        EmpSalaryMng_txt4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EmpSalaryMng_txt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmpSalaryMng_txt4.setText("Management");
        ManageEmployee_subMenu_panel1.add(EmpSalaryMng_txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 140, 20));

        Emp_salaryMng_back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transperat.png"))); // NOI18N
        ManageEmployee_subMenu_panel1.add(Emp_salaryMng_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 162, 175, 175));

        Emp_atendance_Icon1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Emp_atendance_Icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Emp_atendance_Icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Attendance.png"))); // NOI18N
        Emp_atendance_Icon1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Emp_atendance_Icon1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Emp_atendance_Icon1MouseMoved(evt);
            }
        });
        Emp_atendance_Icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Emp_atendance_Icon1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Emp_atendance_Icon1MouseExited(evt);
            }
        });
        ManageEmployee_subMenu_panel1.add(Emp_atendance_Icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 167, 175, 170));

        Emp_attendance_txt3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Emp_attendance_txt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Emp_attendance_txt3.setText("Employee Attendance &");
        ManageEmployee_subMenu_panel1.add(Emp_attendance_txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 284, 140, 20));

        Emp_attendance_txt4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Emp_attendance_txt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Emp_attendance_txt4.setText("Leave Management");
        ManageEmployee_subMenu_panel1.add(Emp_attendance_txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 300, 140, 20));

        Emp_atendance_back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transperat.png"))); // NOI18N
        ManageEmployee_subMenu_panel1.add(Emp_atendance_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 162, 175, 175));

        Manage_employee_back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ManageEmployee_subMenu.png"))); // NOI18N
        ManageEmployee_subMenu_panel1.add(Manage_employee_back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Main_menu_LayeredPane.add(ManageEmployee_subMenu_panel1);
        ManageEmployee_subMenu_panel1.setBounds(0, 0, 1110, 530);

        DetailPanal.add(Main_menu_LayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1110, 530));

        getContentPane().add(DetailPanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 53, 1110, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logUserImgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logUserImgMouseExited
        logUserImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_logUserImgMouseExited

    private void logUserImgMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logUserImgMouseMoved
        logUserImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 96, 125)));//37,4,70
        signOut_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
        Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37,4,70)));
//        Details.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37,4,70)));
//        Confirm_request.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37,4,70)));
//        Report.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37,4,70)));
//
//        ADD_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37,4,70)));
//        Attend_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37,4,70)));
//        EmpDetail_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37,4,70)));
//        Request_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37,4,70)));
//        Report_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37,4,70)));
    }//GEN-LAST:event_logUserImgMouseMoved

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        this.setState(JFrame.ICONIFIED); // minimize Button Mouse click event

    }//GEN-LAST:event_MinimizeMouseClicked

    private void MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseExited
        Minimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_MinimizeMouseExited

    private void MinimizeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseMoved
        Minimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 96, 125)));
    }//GEN-LAST:event_MinimizeMouseMoved

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        //Close Button mouse click event
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Do you want to exit", "Exit",dialog);
        if(result == 0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_CancelMouseClicked

    private void CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseExited
        Cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_CancelMouseExited

    private void CancelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseMoved
        Cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

    }//GEN-LAST:event_CancelMouseMoved

    private void TitleBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TitleBarMouseClicked

    private void TitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMousePressed
        //Jframe pressed and dragged Ivent
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_TitleBarMousePressed

    private void TitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMouseDragged
        //mouse dragged even and create mouse x & y axie
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_TitleBarMouseDragged

    private void InfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoMouseExited
        Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_InfoMouseExited

    private void InfoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoMouseMoved
        Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 96, 125)));//37,4,70
        logUserImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
        signOut_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
        
    }//GEN-LAST:event_InfoMouseMoved

    private void Other_login_signMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Other_login_signMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Other_login_signMouseExited

    private void Other_login_signMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Other_login_signMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Other_login_signMouseMoved

    private void signOut_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOut_buttonMouseExited
        signOut_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_signOut_buttonMouseExited

    private void signOut_buttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOut_buttonMouseMoved
        signOut_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 96, 125)));//37,4,70
        logUserImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
        Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37,4,70)));
    }//GEN-LAST:event_signOut_buttonMouseMoved

    private void signOut_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOut_buttonMouseClicked
            //this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            //this.setCursor(Cursor.getDefaultCursor());
            
        MainHome home = new MainHome();
        home.setVisible(true);
        this.dispose();
        
//            User_login.setVisible(true);
//            logUserImg.setVisible(false);
//            Show_Uname.setVisible(false);
//            Uname_Separator.setVisible(false);
//            signOut_button.setVisible(false);
//            Admin_login_sign1.setVisible(false);
//            ExpandArrow.setVisible(false);
//            Other_login_sign.hide();
//            CollapseArrow.hide();
//            
//           Admin_menu_panel.setVisible(false);
//           NonUser_menu_panel.setVisible(true);
//           Employees_back2.setVisible(false);
//           User_menu_panel.setVisible(false);
//           ManageEmployee_subMenu_panel.setVisible(false);
//           ManageEmployee_subMenu_panel1.setVisible(false);
       
            
    }//GEN-LAST:event_signOut_buttonMouseClicked

    private void Main_menu_LayeredPaneMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_menu_LayeredPaneMouseMoved
        
    }//GEN-LAST:event_Main_menu_LayeredPaneMouseMoved

    private void Inventory_icon1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_icon1MouseMoved
        Inventory_back1.setVisible(true);

    }//GEN-LAST:event_Inventory_icon1MouseMoved

    private void Inventory_icon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_icon1MouseExited
        Inventory_back1.setVisible(false);
        
    }//GEN-LAST:event_Inventory_icon1MouseExited

    private void Item_icon1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_icon1MouseMoved
        Item_back1.setVisible(true);

    }//GEN-LAST:event_Item_icon1MouseMoved

    private void Item_icon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_icon1MouseExited
        Item_back1.setVisible(false);
        
    }//GEN-LAST:event_Item_icon1MouseExited

    private void Sales_Icon1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sales_Icon1MouseMoved
        Sales_back1.setVisible(true);

    }//GEN-LAST:event_Sales_Icon1MouseMoved

    private void Sales_Icon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sales_Icon1MouseExited
        Sales_back1.setVisible(false);
        
    }//GEN-LAST:event_Sales_Icon1MouseExited

    private void Claims_Icon1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Claims_Icon1MouseMoved
        Claims_back1.setVisible(true);

    }//GEN-LAST:event_Claims_Icon1MouseMoved

    private void Claims_Icon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Claims_Icon1MouseExited
        Claims_back1.setVisible(false);
        
    }//GEN-LAST:event_Claims_Icon1MouseExited

    private void Customers_Icon1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customers_Icon1MouseMoved
        Customers_back1.setVisible(true);

    }//GEN-LAST:event_Customers_Icon1MouseMoved

    private void Customers_Icon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customers_Icon1MouseExited
        Customers_back1.setVisible(false);
    }//GEN-LAST:event_Customers_Icon1MouseExited

    private void Jobs_Icon1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jobs_Icon1MouseMoved
        Jobs_back1.setVisible(true);

    }//GEN-LAST:event_Jobs_Icon1MouseMoved

    private void Jobs_Icon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jobs_Icon1MouseExited
        Jobs_back1.setVisible(false);
        
    }//GEN-LAST:event_Jobs_Icon1MouseExited

    private void Employees_Icon1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employees_Icon1MouseMoved
        Employees_back1.setVisible(true);

    }//GEN-LAST:event_Employees_Icon1MouseMoved

    private void Employees_Icon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employees_Icon1MouseExited
        Employees_back1.setVisible(false);
        
    }//GEN-LAST:event_Employees_Icon1MouseExited

    private void manage_employee_close2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_employee_close2MouseClicked
  
        User_menu_panel.setVisible(true);
        ManageEmployee_subMenu_panel1.setVisible(false);
    }//GEN-LAST:event_manage_employee_close2MouseClicked

    private void manage_employee_close2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_employee_close2MouseExited
        manage_employee_close2.setBorder(null);
    }//GEN-LAST:event_manage_employee_close2MouseExited

    private void manage_employee_close2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_employee_close2MouseMoved
        manage_employee_close2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

    }//GEN-LAST:event_manage_employee_close2MouseMoved

    private void Emp_salaryMng_Icon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Emp_salaryMng_Icon1MouseExited
        Emp_salaryMng_back1.setVisible(false);
        
    }//GEN-LAST:event_Emp_salaryMng_Icon1MouseExited

    private void Emp_salaryMng_Icon1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Emp_salaryMng_Icon1MouseMoved
        Emp_salaryMng_back1.setVisible(true);

    }//GEN-LAST:event_Emp_salaryMng_Icon1MouseMoved

    private void Emp_atendance_Icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Emp_atendance_Icon1MouseClicked
        Emp_mng_Admin Emp_Attend = new Emp_mng_Admin();
        Emp_Attend.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Emp_atendance_Icon1MouseClicked

    private void Emp_atendance_Icon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Emp_atendance_Icon1MouseExited
        Emp_atendance_back1.setVisible(false);
        
    }//GEN-LAST:event_Emp_atendance_Icon1MouseExited

    private void Emp_atendance_Icon1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Emp_atendance_Icon1MouseMoved
        Emp_atendance_back1.setVisible(true);

    }//GEN-LAST:event_Emp_atendance_Icon1MouseMoved

    private void Employees_Icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employees_Icon1MouseClicked
    
        User_menu_panel.setVisible(false);
        ManageEmployee_subMenu_panel1.setVisible(true);
        
        Emp_salaryMng_back1.setVisible(false);
        Emp_atendance_back1.setVisible(false);
    }//GEN-LAST:event_Employees_Icon1MouseClicked

    private void Inventory_icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_icon1MouseClicked
        Inventory_User Invent = new Inventory_User();
        Invent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Inventory_icon1MouseClicked

    private void Sales_Icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sales_Icon1MouseClicked
        RetailSalesHandling_User SalesU = new RetailSalesHandling_User();
        SalesU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Sales_Icon1MouseClicked

    private void Emp_salaryMng_Icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Emp_salaryMng_Icon1MouseClicked
        payroll sallery = new payroll();
        sallery.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Emp_salaryMng_Icon1MouseClicked

    private void Item_icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_icon1MouseClicked
        purchasing_User purchasingU = new purchasing_User();
        purchasingU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Item_icon1MouseClicked

    private void Claims_Icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Claims_Icon1MouseClicked
        Complaint_management_User ComplainU = new Complaint_management_User();
        ComplainU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Claims_Icon1MouseClicked

    private void Customers_Icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customers_Icon1MouseClicked
        Manage_Customer_Supplier_User CustomerU = new Manage_Customer_Supplier_User();
        CustomerU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Customers_Icon1MouseClicked

    private void Jobs_Icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jobs_Icon1MouseClicked
        JobManagement_User JobsU = new JobManagement_User();
        JobsU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jobs_Icon1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Am_Pm;
    private javax.swing.JLabel Cancel;
    private javax.swing.JLabel Claims_Icon1;
    private javax.swing.JLabel Claims_back1;
    private javax.swing.JLabel Claims_txt1;
    private javax.swing.JLabel Clock;
    private javax.swing.JLabel Customers_Icon1;
    private javax.swing.JLabel Customers_back1;
    private javax.swing.JLabel Customers_txt1;
    private javax.swing.JLabel Customers_txt2;
    private javax.swing.JPanel DetailPanal;
    private javax.swing.JLabel EmpSalaryMng_txt3;
    private javax.swing.JLabel EmpSalaryMng_txt4;
    private javax.swing.JLabel Emp_atendance_Icon1;
    private javax.swing.JLabel Emp_atendance_back1;
    private javax.swing.JLabel Emp_attendance_txt3;
    private javax.swing.JLabel Emp_attendance_txt4;
    private javax.swing.JLabel Emp_salaryMng_Icon1;
    private javax.swing.JLabel Emp_salaryMng_back1;
    private javax.swing.JLabel Employees_Icon1;
    private javax.swing.JLabel Employees_back1;
    private javax.swing.JLabel Employees_txt1;
    private javax.swing.JLabel Info;
    private javax.swing.JLabel Inventory_back1;
    private javax.swing.JLabel Inventory_icon1;
    private javax.swing.JLabel Inventory_txt1;
    private javax.swing.JLabel Item_back1;
    private javax.swing.JLabel Item_icon1;
    private javax.swing.JLabel Item_txt1;
    private javax.swing.JLabel Jobs_Icon1;
    private javax.swing.JLabel Jobs_back1;
    private javax.swing.JLabel Jobs_txt1;
    private javax.swing.JLayeredPane Main_menu_LayeredPane;
    private javax.swing.JPanel ManageEmployee_subMenu_panel1;
    private javax.swing.JLabel Manage_employee_back2;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Other_login_sign;
    private javax.swing.JLabel Sales_Icon1;
    private javax.swing.JLabel Sales_back1;
    private javax.swing.JLabel Sales_txt1;
    private javax.swing.JLabel Show_Uname;
    private javax.swing.JPanel SubPanel;
    private javax.swing.JPanel TimeLine;
    private javax.swing.JPanel TitleBar;
    private javax.swing.JSeparator Uname_Separator;
    private javax.swing.JPanel User_menu_panel;
    private javax.swing.JLabel dateLable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logUserImg;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel manage_employee_close2;
    private javax.swing.JLabel signOut_button;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("SLogo.png")));
    }


    


    private void setMenuHide() {
    
        ManageEmployee_subMenu_panel1.setVisible(false);
        
           Inventory_back1.setVisible(false);
           Item_back1.setVisible(false);
           Sales_back1.setVisible(false);
           Claims_back1.setVisible(false);
           Employees_back1.setVisible(false);
           Customers_back1.setVisible(false);
           Jobs_back1.setVisible(false);
    }
}
