/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee_AttendanceMng_Package;


import HomePage_Package.*;
import AppPackage.AnimationClass;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.*;
import DbConnection.*;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
/**
 *
 * @author Teshan Chathushka
 */
public class Emp_mng_noUser extends javax.swing.JFrame {

    /**
     * Creates new form Test2
     */
    int xMouse;//xMouse Global
    int yMouse;//yMouse Global
    int timeRun=0;
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs=null;
    
    public Emp_mng_noUser() {
        initComponents();
        setHide();
        setLocationRelativeTo(null);
        conn=Connect.connectn();
        
        new Thread(){
            public void run(){
                while(timeRun==0)
                {
                    Calendar cal = new GregorianCalendar();
                    
                    int hour=cal.get(Calendar.HOUR);
                    int min=cal.get(Calendar.MINUTE);
                    int sec=cal.get(Calendar.SECOND);
                    int am_pm=cal.get(Calendar.AM_PM);
                    
                    String DayNight="";
                    if(am_pm==1){
                        DayNight="PM";
                    }
                    else{
                        DayNight="AM";
                    }
                    String time =hour+":"+min/*+":"+sec*/;
                    String day_night = DayNight;
                    Clock.setText(time);
                    Am_Pm.setText(day_night);
                }
            }
        }.start();
        //setTime();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MMM-dd");
                 String date=sdf.format(new Date());
                 dateLable.setText(date);
        setIcon();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubPanel = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        TitleBar = new javax.swing.JPanel();
        Minimize = new javax.swing.JLabel();
        Cancel = new javax.swing.JLabel();
        DetailPanal = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Attend_panal = new javax.swing.JPanel();
        Contact_lable1 = new javax.swing.JLabel();
        NIC_for_ID_noUser = new javax.swing.JLabel();
        WorkShift_combo_form = new javax.swing.JComboBox();
        ID_form = new javax.swing.JLabel();
        ContactM = new javax.swing.JLabel();
        Contact_txt_form = new javax.swing.JTextField();
        Submit_Leave_form = new javax.swing.JButton();
        Duration_combo_form = new javax.swing.JComboBox();
        RequestForm_open = new javax.swing.JButton();
        EmpName_noUser = new javax.swing.JLabel();
        NIC_lable1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Emp_ID_Attend = new javax.swing.JLabel();
        EmpID_lable1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        EmpImage_noUser1 = new javax.swing.JLabel();
        EmpImage_noUser2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        IdCodeTxt = new javax.swing.JTextField();
        WorkShift_Form = new javax.swing.JLabel();
        AttendEmp_Button = new javax.swing.JButton();
        EmpId_Form = new javax.swing.JLabel();
        ContactH = new javax.swing.JLabel();
        success = new javax.swing.JLabel();
        Reason_form = new javax.swing.JLabel();
        Emp_name_lable1 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        contact_form = new javax.swing.JLabel();
        NIC_lable2 = new javax.swing.JLabel();
        WorkShift_noUser = new javax.swing.JLabel();
        Duration_form = new javax.swing.JLabel();
        LeaveDate_form = new javax.swing.JLabel();
        Email_form = new javax.swing.JLabel();
        Email_txt_form = new javax.swing.JTextField();
        Ldate_form = new com.toedter.calendar.JDateChooser();
        PageBind3 = new javax.swing.JPanel();
        Reason_area_form_Scroll = new javax.swing.JScrollPane();
        Reason_area_form = new javax.swing.JTextArea();
        Form_cancel = new javax.swing.JButton();
        TpNoError_noUser = new javax.swing.JLabel();
        WorkShiftError_noUser = new javax.swing.JLabel();
        JoinDateError_noUser = new javax.swing.JLabel();
        AddressError_noUser = new javax.swing.JLabel();
        EmailAddressError_noUser = new javax.swing.JLabel();
        IDError_noUser1 = new javax.swing.JLabel();
        IDcheck_ReqForm_panel = new javax.swing.JPanel();
        CheckEmp_button = new javax.swing.JButton();
        IdCodeTxt1 = new javax.swing.JTextField();
        manage_employee_close2 = new javax.swing.JLabel();
        IDError_noUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TimeLine = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        Clock = new javax.swing.JLabel();
        Am_Pm = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubPanel.setBackground(new java.awt.Color(37, 4, 70));
        SubPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Home-32.png"))); // NOI18N
        Home.setToolTipText("Home Page");
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        Home.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HomeMouseMoved(evt);
            }
        });
        SubPanel.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        getContentPane().add(SubPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 50, 710));

        TitleBar.setBackground(new java.awt.Color(255, 255, 255));
        TitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TitleBarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TitleBarMousePressed(evt);
            }
        });
        TitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TitleBarMouseDragged(evt);
            }
        });

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Minimize Window-32 (1).png"))); // NOI18N
        Minimize.setToolTipText("Minimise");
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeMouseExited(evt);
            }
        });
        Minimize.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MinimizeMouseMoved(evt);
            }
        });

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Cancel-32.png"))); // NOI18N
        Cancel.setToolTipText("Close");
        Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelMouseExited(evt);
            }
        });
        Cancel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CancelMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout TitleBarLayout = new javax.swing.GroupLayout(TitleBar);
        TitleBar.setLayout(TitleBarLayout);
        TitleBarLayout.setHorizontalGroup(
            TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleBarLayout.createSequentialGroup()
                .addContainerGap(1013, Short.MAX_VALUE)
                .addComponent(Minimize)
                .addGap(16, 16, 16)
                .addComponent(Cancel)
                .addGap(17, 17, 17))
        );
        TitleBarLayout.setVerticalGroup(
            TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(TitleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1110, -1));

        DetailPanal.setBackground(new java.awt.Color(204, 204, 255));
        DetailPanal.setPreferredSize(new java.awt.Dimension(1110, 550));
        DetailPanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Attend_panal.setBackground(new java.awt.Color(204, 204, 255));
        Attend_panal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contact_lable1.setText("Contact Numbers");
        Attend_panal.add(Contact_lable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 449, 88, -1));

        NIC_for_ID_noUser.setText("99XXXXXXX-V");
        Attend_panal.add(NIC_for_ID_noUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 424, 170, -1));

        WorkShift_combo_form.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please Select", "Weel Alignment", "Ordinary employee", "Management" }));
        WorkShift_combo_form.setToolTipText("Select Woring Area");
        WorkShift_combo_form.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Attend_panal.add(WorkShift_combo_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 137, -1, -1));

        ID_form.setText("AA-XX-XX-XXXX");
        Attend_panal.add(ID_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 90, 148, -1));

        ContactM.setText("077 0 123 123");
        Attend_panal.add(ContactM, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 449, -1, -1));

        Contact_txt_form.setToolTipText("Add Contact No");
        Attend_panal.add(Contact_txt_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 182, 148, -1));

        Submit_Leave_form.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Submit Progress-25.png"))); // NOI18N
        Submit_Leave_form.setText("Submit Leave Form");
        Submit_Leave_form.setToolTipText("Submit your Datails");
        Submit_Leave_form.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit_Leave_form.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Submit_Leave_formMouseMoved(evt);
            }
        });
        Submit_Leave_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_Leave_formActionPerformed(evt);
            }
        });
        Attend_panal.add(Submit_Leave_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 470, -1, 41));

        Duration_combo_form.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        Duration_combo_form.setToolTipText("Select Leaving Duration");
        Attend_panal.add(Duration_combo_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 385, -1, -1));

        RequestForm_open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Exit-25.png"))); // NOI18N
        RequestForm_open.setText("Leave Request Form");
        RequestForm_open.setToolTipText("Show Employee Leave Request Form");
        RequestForm_open.setContentAreaFilled(false);
        RequestForm_open.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RequestForm_open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RequestForm_openMouseExited(evt);
            }
        });
        RequestForm_open.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                RequestForm_openMouseMoved(evt);
            }
        });
        RequestForm_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestForm_openActionPerformed(evt);
            }
        });
        Attend_panal.add(RequestForm_open, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 490, 180, 41));

        EmpName_noUser.setText("A. B. C. Xxxxxxxxxxx");
        Attend_panal.add(EmpName_noUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 374, 170, -1));

        NIC_lable1.setText("NIC No");
        Attend_panal.add(NIC_lable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 424, 88, -1));
        Attend_panal.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 309, 515, 14));

        Emp_ID_Attend.setText("AA-XX-XX-XXXX");
        Attend_panal.add(Emp_ID_Attend, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 349, 170, -1));

        EmpID_lable1.setText("Employee ID");
        Attend_panal.add(EmpID_lable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 349, 88, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmpImage_noUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmpImage_noUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Name Tag-96.png"))); // NOI18N
        jPanel6.add(EmpImage_noUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 122));

        EmpImage_noUser2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmpImage_noUser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Name Tag-96.png"))); // NOI18N
        jPanel6.add(EmpImage_noUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 122));

        Attend_panal.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 341, 116, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Leave Request Form");
        Attend_panal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 153, 28));

        IdCodeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdCodeTxtActionPerformed(evt);
            }
        });
        Attend_panal.add(IdCodeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 26, 106, 28));

        WorkShift_Form.setText("Work Shift");
        Attend_panal.add(WorkShift_Form, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 140, 100, -1));

        AttendEmp_Button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AttendEmp_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Barcode Scanner-32.png"))); // NOI18N
        AttendEmp_Button.setText("Scan ID");
        AttendEmp_Button.setToolTipText("Scam Employee ID Card No");
        AttendEmp_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttendEmp_ButtonActionPerformed(evt);
            }
        });
        Attend_panal.add(AttendEmp_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 72, 156, 47));

        EmpId_Form.setText("Employee ID");
        Attend_panal.add(EmpId_Form, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 90, 100, -1));

        ContactH.setText("033 0 123 123");
        Attend_panal.add(ContactH, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 449, -1, -1));

        success.setBackground(new java.awt.Color(204, 204, 204));
        success.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        success.setForeground(new java.awt.Color(0, 153, 0));
        success.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        success.setText("Marking Successfuly");
        Attend_panal.add(success, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 185, 195, -1));

        Reason_form.setText("Reason");
        Attend_panal.add(Reason_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 228, 100, -1));

        Emp_name_lable1.setText("Employee Name");
        Attend_panal.add(Emp_name_lable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 374, 88, -1));

        error.setBackground(new java.awt.Color(204, 204, 204));
        error.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        error.setForeground(new java.awt.Color(153, 0, 0));
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error.setText("Marking Error");
        Attend_panal.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 213, 195, -1));

        contact_form.setText("Contact No");
        Attend_panal.add(contact_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 185, 100, -1));

        NIC_lable2.setText("Work Shift");
        Attend_panal.add(NIC_lable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 399, 88, -1));

        WorkShift_noUser.setText("Abcdef");
        Attend_panal.add(WorkShift_noUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 399, 170, -1));

        Duration_form.setText("Leave Duration");
        Attend_panal.add(Duration_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 388, 100, -1));

        LeaveDate_form.setText("Leave Date");
        Attend_panal.add(LeaveDate_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 341, 100, -1));

        Email_form.setText("E-mail");
        Attend_panal.add(Email_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 433, 100, -1));

        Email_txt_form.setToolTipText("Add E-mail Address");
        Attend_panal.add(Email_txt_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 430, 155, -1));

        Ldate_form.setToolTipText("Select Leave Date");
        Ldate_form.setDateFormatString("yyyy-MM-dd");
        Attend_panal.add(Ldate_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 341, 155, -1));

        PageBind3.setBackground(new java.awt.Color(153, 153, 153));
        PageBind3.setMinimumSize(new java.awt.Dimension(1, 1));

        javax.swing.GroupLayout PageBind3Layout = new javax.swing.GroupLayout(PageBind3);
        PageBind3.setLayout(PageBind3Layout);
        PageBind3Layout.setHorizontalGroup(
            PageBind3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        PageBind3Layout.setVerticalGroup(
            PageBind3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        Attend_panal.add(PageBind3, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 9, -1, -1));

        Reason_area_form.setColumns(20);
        Reason_area_form.setRows(5);
        Reason_area_form_Scroll.setViewportView(Reason_area_form);

        Attend_panal.add(Reason_area_form_Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 250, 90));

        Form_cancel.setText("Cancel");
        Form_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Form_cancelActionPerformed(evt);
            }
        });
        Attend_panal.add(Form_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 500, -1, 41));

        TpNoError_noUser.setForeground(new java.awt.Color(255, 51, 51));
        TpNoError_noUser.setText(" ! Invalid TelePhone No");
        Attend_panal.add(TpNoError_noUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 130, -1));

        WorkShiftError_noUser.setForeground(new java.awt.Color(255, 51, 51));
        WorkShiftError_noUser.setText(" ! Invalid Selection");
        Attend_panal.add(WorkShiftError_noUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 100, -1));

        JoinDateError_noUser.setForeground(new java.awt.Color(255, 51, 51));
        JoinDateError_noUser.setText(" ! Inavalid Date");
        Attend_panal.add(JoinDateError_noUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 90, -1));

        AddressError_noUser.setForeground(new java.awt.Color(255, 51, 51));
        AddressError_noUser.setText(" ! Empty Text Field");
        Attend_panal.add(AddressError_noUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 190, -1));

        EmailAddressError_noUser.setForeground(new java.awt.Color(255, 51, 51));
        EmailAddressError_noUser.setText(" ! Invalid Email Address");
        Attend_panal.add(EmailAddressError_noUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, 170, -1));

        IDError_noUser1.setForeground(new java.awt.Color(255, 51, 51));
        IDError_noUser1.setText(" ! Invalid ID No");
        Attend_panal.add(IDError_noUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 90, -1));

        jLayeredPane1.add(Attend_panal);
        Attend_panal.setBounds(0, 0, 1110, 550);

        IDcheck_ReqForm_panel.setBackground(new java.awt.Color(204, 204, 255));
        IDcheck_ReqForm_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CheckEmp_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckEmp_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Barcode Scanner-32.png"))); // NOI18N
        CheckEmp_button.setText("Scan ID");
        CheckEmp_button.setToolTipText("Scam Employee ID Card No");
        CheckEmp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckEmp_buttonActionPerformed(evt);
            }
        });
        IDcheck_ReqForm_panel.add(CheckEmp_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 156, 47));

        IdCodeTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdCodeTxt1ActionPerformed(evt);
            }
        });
        IDcheck_ReqForm_panel.add(IdCodeTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 106, 28));

        manage_employee_close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-CancelWhite-32.png"))); // NOI18N
        manage_employee_close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manage_employee_close2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manage_employee_close2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manage_employee_close2MouseExited(evt);
            }
        });
        manage_employee_close2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                manage_employee_close2MouseMoved(evt);
            }
        });
        IDcheck_ReqForm_panel.add(manage_employee_close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 165, -1, 32));

        IDError_noUser.setForeground(new java.awt.Color(255, 51, 51));
        IDError_noUser.setText(" ! Invalid ID No");
        IDcheck_ReqForm_panel.add(IDError_noUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 90, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/leaveRequest_Confirm.png"))); // NOI18N
        IDcheck_ReqForm_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPane1.add(IDcheck_ReqForm_panel);
        IDcheck_ReqForm_panel.setBounds(0, 0, 1110, 550);

        DetailPanal.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 550));

        getContentPane().add(DetailPanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 1110, 555));

        TimeLine.setBackground(new java.awt.Color(204, 204, 204));
        TimeLine.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SLogo.png"))); // NOI18N
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });
        TimeLine.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 120));

        Clock.setFont(new java.awt.Font("Digital-7 Mono", 0, 48)); // NOI18N
        Clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clock.setText("00:00");
        Clock.setToolTipText("Clock");
        TimeLine.add(Clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 11, 128, 53));

        Am_Pm.setFont(new java.awt.Font("Digital-7 Mono", 0, 24)); // NOI18N
        Am_Pm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimeLine.add(Am_Pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1045, 21, 26, 43));

        dateLable.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        dateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLable.setText("00 00 0000");
        TimeLine.add(dateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 70, 212, 38));

        getContentPane().add(TimeLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 44, 1110, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TitleBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TitleBarMouseClicked

    private void TitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMouseDragged
       //mouse dragged even and create mouse x & y axie
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_TitleBarMouseDragged

    private void TitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMousePressed
        //Jframe pressed and dragged Ivent
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_TitleBarMousePressed

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        this.setState(JFrame.ICONIFIED); // minimize Button Mouse click event
        
    }//GEN-LAST:event_MinimizeMouseClicked

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
       //Close Button mouse click event
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Do you want to exit", "Exit",dialog);
        if(result == 0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_CancelMouseClicked

    private void MinimizeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseMoved
        Minimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 96, 125)));
    }//GEN-LAST:event_MinimizeMouseMoved

    private void MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseExited
       Minimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_MinimizeMouseExited

    private void CancelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseMoved
        Cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
    }//GEN-LAST:event_CancelMouseMoved

    private void CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseExited
        Cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_CancelMouseExited

    private void HomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseMoved
        Home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 96, 125)));//37,4,70
        
    }//GEN-LAST:event_HomeMouseMoved

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        Home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37,4,70)));
    }//GEN-LAST:event_HomeMouseExited

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        
    }//GEN-LAST:event_logoMouseClicked

    private void RequestForm_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestForm_openActionPerformed
        Attend_panal.setVisible(false);
        IDcheck_ReqForm_panel.setVisible(true);
        IDError_noUser.setVisible(false);
        IDError_noUser1.setVisible(false);
        
                 Emp_ID_Attend.setText("AA-XX-XX-XXXX");
                 EmpName_noUser.setText("A. B. C. Xxxxxxxxxxx");
                 WorkShift_noUser.setText("Abcdef");
                 NIC_for_ID_noUser.setText("99XXXXXXX-V");
                 ContactM.setText("077 0 123 123");
                 ContactH.setText("033 0 123 123");
                 
                 EmpImage_noUser1.setVisible(false);
                 EmpImage_noUser2.setVisible(true);
        
    }//GEN-LAST:event_RequestForm_openActionPerformed

    private void AttendEmp_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendEmp_ButtonActionPerformed
        
        String EmpID = null;
        String AttendID = IdCodeTxt.getText();
        String CheckImg = null;
        String trueDate=null;
        Date attendDate = new Date();
        SimpleDateFormat time = new SimpleDateFormat("hh:mm");
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String AttDate = date.format(attendDate);
        String Time = time.format(attendDate);
        String FName= null;
        String LName = null;
        String MName = null;
        String HNum  = null;
        String MNum  = null;
        String ID = null;
        String NIC = null;
        String wshift = null;
        String ID_NO = IdCodeTxt.getText();
        //boolean vID = Validate.validate_EmpID(ID);
        
        try {
            String valEmp = "SELECT Emp_ID FROM `emp_details` WHERE Emp_ID = '"+AttendID+"'";
            pst = conn.prepareStatement(valEmp);
            rs = pst.executeQuery();
            while(rs.next()){
                EmpID = rs.getString("Emp_ID");
            }
            
        } catch (Exception e) {
        }
        try {
            String ImgCheckSql = "select Images from `emp_details` where Emp_ID = '"+ID_NO+"'AND Images is null";
            pst = conn.prepareStatement(ImgCheckSql);
            rs = pst.executeQuery();
            while(rs.next()){
                String Abc = "null";
                String x = rs.getString("Images");
                System.out.println(CheckImg);
                if(x == null){
                    CheckImg = "no_Image";
                    System.out.println(CheckImg);
                }
                else{
                    System.out.println("vada na neeeeee....!");
                    
                }
                System.out.println(CheckImg);
            }
        } catch (Exception e) {
        }
        
        if(AttendID.equals(EmpID)){
            IDError_noUser1.setVisible(false);
            
             
            //-----Check GetDate-----------
        try {
            
            String det = "select Date from emp_attendance where Date = '"+AttDate+"' AND Emp_ID = '"+AttendID+"'";
            pst = conn.prepareStatement(det);
            rs = pst.executeQuery();
            while(rs.next()){
                trueDate=rs.getString("Date");
            }
            
        } catch (Exception e) {
            System.out.println("det quary error..");
        }
        //^^^^^^^^^Check GetDate^^^^^^^
        
        if(AttDate.equals(trueDate)){
            //---------Update Out Time------------
            try {
                
                String outTime="UPDATE emp_attendance SET Out_time = '"+Time+"' WHERE Date = '"+AttDate+"'";
                pst = conn.prepareStatement(outTime);
                pst.execute();
                success.setVisible(true);
                error.setVisible(false);
                IdCodeTxt.setText("");
                success.setText("Marking Successfuly,Good Bye");
             }
            catch (Exception e) {
            System.out.println(e);
            error.setVisible(true);
            success.setVisible(false);
            error.setText("Error,Can't Insert the OutTime");
            }
            //^^^^^^Update Out Time^^^^^^^
            if(CheckImg == "no_Image"){
                //Show Employee Details------------
            
                try {
                String att_Sql = "select Emp_ID,F_name,M_name,L_name,NIC,HTP,MTP,Work_Shift,Images from emp_details where Emp_ID = '"+ID_NO+"'";
                pst = conn.prepareStatement(att_Sql);
                rs = pst.executeQuery();
            
            while(rs.next()){
                
                ID = rs.getString("Emp_ID");
                FName = rs.getString("F_name");
                MName = rs.getString("M_name");
                LName = rs.getString("L_name");
                NIC = rs.getString("NIC");
                HNum = rs.getString("HTP");
                MNum = rs.getString("MTP");
                wshift = rs.getString("Work_Shift");
                //byte[] img = rs.getBytes("Images");
                
//                ImageIcon image = new ImageIcon(img);
//                Image im = image.getImage();
//                Image myImg = im.getScaledInstance(EmpImage_noUser1.getWidth(), EmpImage_noUser1.getHeight(), Image.SCALE_SMOOTH);
//                ImageIcon newImage = new ImageIcon(myImg);
                EmpImage_noUser1.setVisible(false);
                EmpImage_noUser2.setVisible(true);
                
                //EmpImage_noUser1.setIcon(newImage);
                Emp_ID_Attend.setText(ID);
                WorkShift_noUser.setText(wshift);
                
           }
            //Name Genarate----------
                String NameResult1,NameResult2,NameResult3;
       
                NameResult1=FName.substring(0,1).toUpperCase();
                NameResult2=MName.substring(0,1).toUpperCase();
                NameResult3=LName;
       
                EmpName_noUser.setText(NameResult1+". "+NameResult2+". "+NameResult3);
            //----------------
                //NIC NO Genarate----------
                    String NICResult1,NICResult2;
       
                    NICResult1=NIC.substring(0,9);
                    NICResult2=NIC.substring(9,10).toUpperCase();
       
                    NIC_for_ID_noUser.setText(NICResult1+"-"+NICResult2);
                //-------------
                    
                //Genarate Tp Numbers-------
                    String HTPresult1,HTPresult2,HTPresult3,HTPresult4;
                    String MTPresult1,MTPresult2,MTPresult3,MTPresult4;
       
                    HTPresult1=HNum.substring(0,3);
                    HTPresult2=HNum.substring(3,4);
                    HTPresult3=HNum.substring(4,7);
                    HTPresult4=HNum.substring(7,10);
       
                    MTPresult1=MNum.substring(0,3);
                    MTPresult2=MNum.substring(3,4);
                    MTPresult3=MNum.substring(4,7);
                    MTPresult4=MNum.substring(7,10);
       
                ContactM.setText(HTPresult1+" "+HTPresult2+" "+HTPresult3+" "+HTPresult4);
                ContactH.setText(MTPresult1+" "+MTPresult2+" "+MTPresult3+" "+MTPresult4);
                //--------------
                
            } catch (SQLException ex) {
                System.out.println("Out Time Error...... "+ex);
                error.setVisible(true);
                success.setVisible(false);
                error.setText("Error,Can't Show Details");
            } 
            //^^^^^^^^^Show Employee Details^^^^^^^^^^
            }
            else{
               //Show Employee Details------------
            
                try {
                String att_Sql = "select Emp_ID,F_name,M_name,L_name,NIC,HTP,MTP,Work_Shift,Images from emp_details where Emp_ID = '"+ID_NO+"'";
                pst = conn.prepareStatement(att_Sql);
                rs = pst.executeQuery();
            
            while(rs.next()){
                
                ID = rs.getString("Emp_ID");
                FName = rs.getString("F_name");
                MName = rs.getString("M_name");
                LName = rs.getString("L_name");
                NIC = rs.getString("NIC");
                HNum = rs.getString("HTP");
                MNum = rs.getString("MTP");
                wshift = rs.getString("Work_Shift");
                byte[] img = rs.getBytes("Images");
                
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(EmpImage_noUser1.getWidth(), EmpImage_noUser1.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                EmpImage_noUser1.setVisible(true);
                EmpImage_noUser2.setVisible(false);
                
                EmpImage_noUser1.setIcon(newImage);
                Emp_ID_Attend.setText(ID);
                WorkShift_noUser.setText(wshift);
                
           }
            //Name Genarate----------
                String NameResult1,NameResult2,NameResult3;
       
                NameResult1=FName.substring(0,1).toUpperCase();
                NameResult2=MName.substring(0,1).toUpperCase();
                NameResult3=LName;
       
                EmpName_noUser.setText(NameResult1+". "+NameResult2+". "+NameResult3);
            //----------------
                //NIC NO Genarate----------
                    String NICResult1,NICResult2;
       
                    NICResult1=NIC.substring(0,9);
                    NICResult2=NIC.substring(9,10).toUpperCase();
       
                    NIC_for_ID_noUser.setText(NICResult1+"-"+NICResult2);
                //-------------
                    
                //Genarate Tp Numbers-------
                    String HTPresult1,HTPresult2,HTPresult3,HTPresult4;
                    String MTPresult1,MTPresult2,MTPresult3,MTPresult4;
       
                    HTPresult1=HNum.substring(0,3);
                    HTPresult2=HNum.substring(3,4);
                    HTPresult3=HNum.substring(4,7);
                    HTPresult4=HNum.substring(7,10);
       
                    MTPresult1=MNum.substring(0,3);
                    MTPresult2=MNum.substring(3,4);
                    MTPresult3=MNum.substring(4,7);
                    MTPresult4=MNum.substring(7,10);
       
                ContactM.setText(HTPresult1+" "+HTPresult2+" "+HTPresult3+" "+HTPresult4);
                ContactH.setText(MTPresult1+" "+MTPresult2+" "+MTPresult3+" "+MTPresult4);
                //--------------
                
            } catch (SQLException ex) {
                System.out.println("Out Time Error...... "+ex);
                error.setVisible(true);
                success.setVisible(false);
                error.setText("Error,Can't Show Details");
            } 
            //^^^^^^^^^Show Employee Details^^^^^^^^^^ 
            }
            
        }
        
        else{
            try {
            //-------Insert Employee Attendance Time---------
            String attendSQL ="insert into emp_attendance(Emp_ID,Date,Come_time) values ('"+AttendID+"','"+AttDate+"','"+Time+"')"; 
            pst = conn.prepareStatement(attendSQL);
            pst.execute();
                success.setVisible(true);
                    error.setVisible(false);
                    success.setText("Marking Successfuly,Welcome");
                IdCodeTxt.setText("");
            
            } 
            catch (Exception e) {
            System.out.println("insert emp attend error..... "+e);
                error.setVisible(true);
                success.setVisible(false);
                error.setText("Error,Can't Mark Attendece");
                }
            //^^^^^^Insert Employee Attendance Time^^^^^^^
            if(CheckImg == "no_Image"){
                //Show Employee Details------------
            
                try {
                String att_Sql = "select Emp_ID,F_name,M_name,L_name,NIC,HTP,MTP,Work_Shift,Images from emp_details where Emp_ID = '"+ID_NO+"'";
                pst = conn.prepareStatement(att_Sql);
                rs = pst.executeQuery();
            
            while(rs.next()){
                
                ID = rs.getString("Emp_ID");
                FName = rs.getString("F_name");
                MName = rs.getString("M_name");
                LName = rs.getString("L_name");
                NIC = rs.getString("NIC");
                HNum = rs.getString("HTP");
                MNum = rs.getString("MTP");
                wshift = rs.getString("Work_Shift");
                //byte[] img = rs.getBytes("Images");
                
//                ImageIcon image = new ImageIcon(img);
//                Image im = image.getImage();
//                Image myImg = im.getScaledInstance(EmpImage_noUser1.getWidth(), EmpImage_noUser1.getHeight(), Image.SCALE_SMOOTH);
//                ImageIcon newImage = new ImageIcon(myImg);
                EmpImage_noUser1.setVisible(false);
                EmpImage_noUser2.setVisible(true);
                
                //EmpImage_noUser1.setIcon(newImage);
                Emp_ID_Attend.setText(ID);
                WorkShift_noUser.setText(wshift);
                
           }
            //Name Genarate----------
                String NameResult1,NameResult2,NameResult3;
       
                NameResult1=FName.substring(0,1).toUpperCase();
                NameResult2=MName.substring(0,1).toUpperCase();
                NameResult3=LName;
       
                EmpName_noUser.setText(NameResult1+". "+NameResult2+". "+NameResult3);
            //----------------
                //NIC NO Genarate----------
                    String NICResult1,NICResult2;
       
                    NICResult1=NIC.substring(0,9);
                    NICResult2=NIC.substring(9,10).toUpperCase();
       
                    NIC_for_ID_noUser.setText(NICResult1+"-"+NICResult2);
                //-------------
                    
                //Genarate Tp Numbers-------
                    String HTPresult1,HTPresult2,HTPresult3,HTPresult4;
                    String MTPresult1,MTPresult2,MTPresult3,MTPresult4;
       
                    HTPresult1=HNum.substring(0,3);
                    HTPresult2=HNum.substring(3,4);
                    HTPresult3=HNum.substring(4,7);
                    HTPresult4=HNum.substring(7,10);
       
                    MTPresult1=MNum.substring(0,3);
                    MTPresult2=MNum.substring(3,4);
                    MTPresult3=MNum.substring(4,7);
                    MTPresult4=MNum.substring(7,10);
       
                ContactM.setText(HTPresult1+" "+HTPresult2+" "+HTPresult3+" "+HTPresult4);
                ContactH.setText(MTPresult1+" "+MTPresult2+" "+MTPresult3+" "+MTPresult4);
                //--------------
                
            } catch (SQLException ex) {
                System.out.println("Out Time Error...... "+ex);
                error.setVisible(true);
                success.setVisible(false);
                error.setText("Error,Can't Show Details");
            } 
            //^^^^^^^^^Show Employee Details^^^^^^^^^^
            }
            else{
                //Show Employee Details------------
            
                try {
                String att_Sql = "select Emp_ID,F_name,M_name,L_name,NIC,HTP,MTP,Work_Shift,Images from emp_details where Emp_ID = '"+ID_NO+"'";
                pst = conn.prepareStatement(att_Sql);
                rs = pst.executeQuery();
            
            while(rs.next()){
                
                ID = rs.getString("Emp_ID");
                FName = rs.getString("F_name");
                MName = rs.getString("M_name");
                LName = rs.getString("L_name");
                NIC = rs.getString("NIC");
                HNum = rs.getString("HTP");
                MNum = rs.getString("MTP");
                wshift = rs.getString("Work_Shift");
                byte[] img = rs.getBytes("Images");
                
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(EmpImage_noUser1.getWidth(), EmpImage_noUser1.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                EmpImage_noUser1.setVisible(true);
                EmpImage_noUser2.setVisible(false);
                
                EmpImage_noUser1.setIcon(newImage);
                Emp_ID_Attend.setText(ID);
                WorkShift_noUser.setText(wshift);
                
           }
            //Name Genarate----------
                String NameResult1,NameResult2,NameResult3;
       
                NameResult1=FName.substring(0,1).toUpperCase();
                NameResult2=MName.substring(0,1).toUpperCase();
                NameResult3=LName;
       
                EmpName_noUser.setText(NameResult1+". "+NameResult2+". "+NameResult3);
            //----------------
                //NIC NO Genarate----------
                    String NICResult1,NICResult2;
       
                    NICResult1=NIC.substring(0,9);
                    NICResult2=NIC.substring(9,10).toUpperCase();
       
                    NIC_for_ID_noUser.setText(NICResult1+"-"+NICResult2);
                //-------------
                    
                //Genarate Tp Numbers-------
                    String HTPresult1,HTPresult2,HTPresult3,HTPresult4;
                    String MTPresult1,MTPresult2,MTPresult3,MTPresult4;
       
                    HTPresult1=HNum.substring(0,3);
                    HTPresult2=HNum.substring(3,4);
                    HTPresult3=HNum.substring(4,7);
                    HTPresult4=HNum.substring(7,10);
       
                    MTPresult1=MNum.substring(0,3);
                    MTPresult2=MNum.substring(3,4);
                    MTPresult3=MNum.substring(4,7);
                    MTPresult4=MNum.substring(7,10);
       
                ContactM.setText(HTPresult1+" "+HTPresult2+" "+HTPresult3+" "+HTPresult4);
                ContactH.setText(MTPresult1+" "+MTPresult2+" "+MTPresult3+" "+MTPresult4);
                //--------------
                
            } catch (SQLException ex) {
                System.out.println("Out Time Error...... "+ex);
                error.setVisible(true);
                success.setVisible(false);
                error.setText("Error,Can't Show Details");
            } 
            //^^^^^^^^^Show Employee Details^^^^^^^^^^
            }
            
            }
        }
        else if(AttendID.isEmpty()){
            IDError_noUser1.setVisible(true);
            success.setVisible(false);
        }
        else{
            IDError_noUser1.setVisible(true);
            success.setVisible(false);
        }
        
        
       
    }//GEN-LAST:event_AttendEmp_ButtonActionPerformed

    private void Submit_Leave_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_Leave_formActionPerformed
            Date attendDate = new Date();
            SimpleDateFormat time = new SimpleDateFormat("hh:mm");
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            String ReqDate = date.format(attendDate);
          
            
            String ID = ID_form.getText();
            String WS = (String) WorkShift_combo_form.getSelectedItem();
            String contact = Contact_txt_form.getText();
            String reason = Reason_area_form.getText();
            String leaveDate = ((JTextField)Ldate_form.getDateEditor().getUiComponent()).getText();
            String duration = (String) Duration_combo_form.getSelectedItem();
            String email = Email_txt_form.getText();
            String tname=null;
        
             boolean vContact = Validate.validateTpNo(contact);
             boolean vEmail = Validate.validateEmail(email);
             boolean vReason = Validate.check_Null(reason);
             
             if(WS.equals("Please Select")){
                 WorkShiftError_noUser.setVisible(true);
             }
             else{
                 WorkShiftError_noUser.setVisible(false);
                 form1 = true;
             }
             if(vContact){
                 TpNoError_noUser.setVisible(false);
                 form2 = true;
             }
             else{
                 TpNoError_noUser.setVisible(true);
                 
             }
             if(vReason){
                 AddressError_noUser.setVisible(false);
                 form3 = true;
             }
             else{
                 AddressError_noUser.setVisible(true);
             }
             if(leaveDate.isEmpty()){
                 JoinDateError_noUser.setVisible(true);
             }
             else{
                 JoinDateError_noUser.setVisible(false);
                 form4 = true;
             }
             if(vEmail){
                 EmailAddressError_noUser.setVisible(false);
                 form5 = true;
             }
             else{
                 EmailAddressError_noUser.setVisible(true);
             }
             if((form1 == true) && (form2 == true) && (form3 == true) && (form4 == true) && (form5 == true)){
                 int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Submit the Request Click 'Yes',Edit or some thing Click 'No'", "Submit Leave Request",dialog);
        if(result == 0)
        {
            
            
            try {
                String serchName = "SELECT CONCAT(F_name,' ',M_name)AS name FROM `emp_details` WHERE Emp_ID = '"+ID+"'";
                    pst = conn.prepareStatement(serchName);
                    rs = pst.executeQuery(serchName);
                    while(rs.next()){
                        tname = rs.getString("name");
                    }
            } catch (Exception e) {
                System.out.println("Serch name error in Request form...."+e);
            }
            
            try {
                
                String formSql = "insert into leave_request(Emp_ID,Emp_Name,Work_Shift,Contact_No,Reason,Request_Date,Leave_Date,Duration,Email) values('"+ID+"','"+tname+"','"+WS+"','"+contact+"','"+reason+"','"+ReqDate+"','"+leaveDate+"','"+duration+"','"+email+"')";
                pst = conn.prepareStatement(formSql);
                pst.execute();
                System.out.println("Id");
                //'"+tname+"', emp_name,
            } catch (Exception e) {
                System.out.println("Requst insert error....");
            }
            
            WorkShift_combo_form.setSelectedItem("Please Select");
            Contact_txt_form.setText("");
            Reason_area_form.setText("");
            Ldate_form.setDate(null);
            Duration_combo_form.setSelectedItem("1");
            Email_txt_form.setText("");
            
            success.setVisible(false);
            error.setVisible(false);
            RequestForm_open.setVisible(false);
            EmpId_Form.setVisible(false);
            ID_form.setVisible(false);
            WorkShift_Form.setVisible(false);
            WorkShift_combo_form.setVisible(false);
            contact_form.setVisible(false);
            Contact_txt_form.setVisible(false);
            Reason_form.setVisible(false);
            Reason_area_form.setVisible(false);
            Reason_area_form_Scroll.setVisible(false);
            LeaveDate_form.setVisible(false);
            Ldate_form.setVisible(false);
            Duration_form.setVisible(false);
            Duration_combo_form.setVisible(false);
            Email_form.setVisible(false);
            Email_txt_form.setVisible(false);
            Submit_Leave_form.setVisible(false);
            Form_cancel.setVisible(false);
            
                 Emp_ID_Attend.setText("AA-XX-XX-XXXX");
                 EmpName_noUser.setText("A. B. C. Xxxxxxxxxxx");
                 WorkShift_noUser.setText("Abcdef");
                 NIC_for_ID_noUser.setText("99XXXXXXX-V");
                 ContactM.setText("077 0 123 123");
                 ContactH.setText("033 0 123 123");
                 
                 EmpImage_noUser1.setVisible(false);
                 EmpImage_noUser2.setVisible(true);
            
            IdCodeTxt.setVisible(true);
            AttendEmp_Button.setVisible(true);
            success.setVisible(false);
            error.setVisible(false);
            RequestForm_open.setVisible(true);
                 }
                 
             }
             else{
                 try{
               
             } catch (Exception e) {
                 System.out.println(e);
              JOptionPane.showMessageDialog(this,e);
           }
             }
        
        
    }//GEN-LAST:event_Submit_Leave_formActionPerformed

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Do you want to go Homepage", "Exit",dialog);
        if(result == 0)
        {
            MainHome home1 = new MainHome();
            home1.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_HomeMouseClicked

    private void IdCodeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdCodeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdCodeTxtActionPerformed

    private void CheckEmp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckEmp_buttonActionPerformed
        
        String ID = IdCodeTxt1.getText();
        String EmpID = null;
        String FName= null;
        String LName = null;
        String MName = null;
        String HNum  = null;
        String MNum  = null;
        //String ID = null;
        String NIC = null;
        String wshift = null;
        boolean vID = Validate.validate_EmpID(ID);
        
        try {
            String valEmp = "SELECT Emp_ID FROM `emp_details` WHERE Emp_ID = '"+ID+"'";
            pst = conn.prepareStatement(valEmp);
            rs = pst.executeQuery();
            while(rs.next()){
                EmpID = rs.getString("Emp_ID");
            }
            
        } catch (Exception e) {
        }
        
        
        if(ID.equals(EmpID) ){
            IDError_noUser.setVisible(false);
            IdCodeTxt1.setText("");
            ID_form.setText(EmpID);
            
            Attend_panal.setVisible(true);
            IDcheck_ReqForm_panel.setVisible(false);
        
            EmpId_Form.setVisible(true);
            ID_form.setVisible(true);
            WorkShift_Form.setVisible(true);
            WorkShift_combo_form.setVisible(true);
            contact_form.setVisible(true);
            Contact_txt_form.setVisible(true);
            Reason_form.setVisible(true);
            Reason_area_form.setVisible(true);
            Reason_area_form_Scroll.setVisible(true);
            LeaveDate_form.setVisible(true);
            Ldate_form.setVisible(true);
            Duration_form.setVisible(true);
            Duration_combo_form.setVisible(true);
            Email_form.setVisible(true);
            Email_txt_form.setVisible(true);
            Submit_Leave_form.setVisible(true);
            Form_cancel.setVisible(true);
            
            IdCodeTxt.setVisible(false);
            AttendEmp_Button.setVisible(false);
            success.setVisible(false);
            error.setVisible(false);
            RequestForm_open.setVisible(false);
            
            
            //Show Employee Details------------
            
                try {
                String att_Sql = "select Emp_ID,F_name,M_name,L_name,NIC,HTP,MTP,Work_Shift,Images from emp_details where Emp_ID = '"+ID+"'";
                pst = conn.prepareStatement(att_Sql);
                rs = pst.executeQuery();
            
            while(rs.next()){
                
                ID = rs.getString("Emp_ID");
                FName = rs.getString("F_name");
                MName = rs.getString("M_name");
                LName = rs.getString("L_name");
                NIC = rs.getString("NIC");
                HNum = rs.getString("HTP");
                MNum = rs.getString("MTP");
                wshift = rs.getString("Work_Shift");
                byte[] img = rs.getBytes("Images");
                
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(EmpImage_noUser1.getWidth(), EmpImage_noUser1.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                EmpImage_noUser1.setVisible(true);
                EmpImage_noUser2.setVisible(false);
                
                EmpImage_noUser1.setIcon(newImage);
                Emp_ID_Attend.setText(ID);
                WorkShift_noUser.setText(wshift);
                
           }
            //Name Genarate----------
                String NameResult1,NameResult2,NameResult3;
       
                NameResult1=FName.substring(0,1).toUpperCase();
                NameResult2=MName.substring(0,1).toUpperCase();
                NameResult3=LName;
       
                EmpName_noUser.setText(NameResult1+". "+NameResult2+". "+NameResult3);
            //----------------
                //NIC NO Genarate----------
                    String NICResult1,NICResult2;
       
                    NICResult1=NIC.substring(0,9);
                    NICResult2=NIC.substring(9,10).toUpperCase();
       
                    NIC_for_ID_noUser.setText(NICResult1+"-"+NICResult2);
                //-------------
                    
                //Genarate Tp Numbers-------
                    String HTPresult1,HTPresult2,HTPresult3,HTPresult4;
                    String MTPresult1,MTPresult2,MTPresult3,MTPresult4;
       
                    HTPresult1=HNum.substring(0,3);
                    HTPresult2=HNum.substring(3,4);
                    HTPresult3=HNum.substring(4,7);
                    HTPresult4=HNum.substring(7,10);
       
                    MTPresult1=MNum.substring(0,3);
                    MTPresult2=MNum.substring(3,4);
                    MTPresult3=MNum.substring(4,7);
                    MTPresult4=MNum.substring(7,10);
       
                ContactM.setText(HTPresult1+" "+HTPresult2+" "+HTPresult3+" "+HTPresult4);
                ContactH.setText(MTPresult1+" "+MTPresult2+" "+MTPresult3+" "+MTPresult4);
                //--------------
                
            } catch (SQLException ex) {
                System.out.println("Out Time Error...... "+ex);
                error.setVisible(true);
                success.setVisible(false);
                error.setText("Error,Can't Show Details");
            } 
            //^^^^^^^^^Show Employee Details^^^^^^^^^^
            
        }
        else if(ID.isEmpty()){
            IDError_noUser.setVisible(true);
        }
        else{
            IDError_noUser.setVisible(true);
        }
        

        
    }//GEN-LAST:event_CheckEmp_buttonActionPerformed

    private void IdCodeTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdCodeTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdCodeTxt1ActionPerformed

    private void manage_employee_close2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_employee_close2MouseClicked

        Attend_panal.setVisible(true);
        IDcheck_ReqForm_panel.setVisible(false);
        success.setVisible(false);
        error.setVisible(false);
        
        
    }//GEN-LAST:event_manage_employee_close2MouseClicked

    private void manage_employee_close2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_employee_close2MouseExited
        manage_employee_close2.setBorder(null);
    }//GEN-LAST:event_manage_employee_close2MouseExited

    private void manage_employee_close2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_employee_close2MouseMoved
        manage_employee_close2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
    }//GEN-LAST:event_manage_employee_close2MouseMoved

    private void RequestForm_openMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RequestForm_openMouseMoved
        RequestForm_open.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,102)));
    }//GEN-LAST:event_RequestForm_openMouseMoved

    private void RequestForm_openMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RequestForm_openMouseExited
        RequestForm_open.setBorder(null);
    }//GEN-LAST:event_RequestForm_openMouseExited

    private void Form_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Form_cancelActionPerformed
        
        WorkShift_combo_form.setSelectedItem("Please Select");
        Contact_txt_form.setText("");
        Reason_area_form.setText("");
        Ldate_form.setDate(null);
        Duration_combo_form.setSelectedItem("1");
        Email_txt_form.setText("");
                    //Employee Details Reset
                 Emp_ID_Attend.setText("AA-XX-XX-XXXX");
                 EmpName_noUser.setText("A. B. C. Xxxxxxxxxxx");
                 WorkShift_noUser.setText("Abcdef");
                 NIC_for_ID_noUser.setText("99XXXXXXX-V");
                 ContactM.setText("077 0 123 123");
                 ContactH.setText("033 0 123 123");
                 
                 EmpImage_noUser1.setVisible(false);
                 EmpImage_noUser2.setVisible(true);
        
        EmpId_Form.setVisible(false);
        ID_form.setVisible(false);
        WorkShift_Form.setVisible(false);
        WorkShift_combo_form.setVisible(false);
        contact_form.setVisible(false);
        Contact_txt_form.setVisible(false);
        Reason_form.setVisible(false);
        Reason_area_form_Scroll.setVisible(false);
        Reason_area_form.hide();
        LeaveDate_form.setVisible(false);
        Ldate_form.setVisible(false);
        Duration_form.setVisible(false);
        Duration_combo_form.setVisible(false);
        Email_form.setVisible(false);
        Email_txt_form.setVisible(false);
        Submit_Leave_form.setVisible(false);
        Form_cancel.setVisible(false);
        
        WorkShiftError_noUser.setVisible(false);
        TpNoError_noUser.setVisible(false);
        AddressError_noUser.setVisible(false);
        JoinDateError_noUser.setVisible(false);
        EmailAddressError_noUser.setVisible(false);
        
        
        IdCodeTxt.setVisible(true);
        AttendEmp_Button.setVisible(true);
        success.setVisible(false);
        error.setVisible(false);
        RequestForm_open.setVisible(true);
        
    }//GEN-LAST:event_Form_cancelActionPerformed

    private void manage_employee_close2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_employee_close2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_manage_employee_close2MouseEntered

    private void Submit_Leave_formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Submit_Leave_formMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Submit_Leave_formMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emp_mng_noUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emp_mng_noUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emp_mng_noUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emp_mng_noUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emp_mng_noUser().setVisible(true);
            }
        });
    }
    
    private boolean form1,form2,form3,form4,form5;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressError_noUser;
    private javax.swing.JLabel Am_Pm;
    private javax.swing.JButton AttendEmp_Button;
    private javax.swing.JPanel Attend_panal;
    private javax.swing.JLabel Cancel;
    private javax.swing.JButton CheckEmp_button;
    private javax.swing.JLabel Clock;
    private javax.swing.JLabel ContactH;
    private javax.swing.JLabel ContactM;
    private javax.swing.JLabel Contact_lable1;
    private javax.swing.JTextField Contact_txt_form;
    private javax.swing.JPanel DetailPanal;
    private javax.swing.JComboBox Duration_combo_form;
    private javax.swing.JLabel Duration_form;
    private javax.swing.JLabel EmailAddressError_noUser;
    private javax.swing.JLabel Email_form;
    private javax.swing.JTextField Email_txt_form;
    private javax.swing.JLabel EmpID_lable1;
    private javax.swing.JLabel EmpId_Form;
    private javax.swing.JLabel EmpImage_noUser1;
    private javax.swing.JLabel EmpImage_noUser2;
    private javax.swing.JLabel EmpName_noUser;
    private javax.swing.JLabel Emp_ID_Attend;
    private javax.swing.JLabel Emp_name_lable1;
    private javax.swing.JButton Form_cancel;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel IDError_noUser;
    private javax.swing.JLabel IDError_noUser1;
    private javax.swing.JLabel ID_form;
    private javax.swing.JPanel IDcheck_ReqForm_panel;
    private javax.swing.JTextField IdCodeTxt;
    private javax.swing.JTextField IdCodeTxt1;
    private javax.swing.JLabel JoinDateError_noUser;
    private com.toedter.calendar.JDateChooser Ldate_form;
    private javax.swing.JLabel LeaveDate_form;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel NIC_for_ID_noUser;
    private javax.swing.JLabel NIC_lable1;
    private javax.swing.JLabel NIC_lable2;
    private javax.swing.JPanel PageBind3;
    private javax.swing.JTextArea Reason_area_form;
    private javax.swing.JScrollPane Reason_area_form_Scroll;
    private javax.swing.JLabel Reason_form;
    private javax.swing.JButton RequestForm_open;
    private javax.swing.JPanel SubPanel;
    private javax.swing.JButton Submit_Leave_form;
    private javax.swing.JPanel TimeLine;
    private javax.swing.JPanel TitleBar;
    private javax.swing.JLabel TpNoError_noUser;
    private javax.swing.JLabel WorkShiftError_noUser;
    private javax.swing.JLabel WorkShift_Form;
    private javax.swing.JComboBox WorkShift_combo_form;
    private javax.swing.JLabel WorkShift_noUser;
    private javax.swing.JLabel contact_form;
    private javax.swing.JLabel dateLable;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel manage_employee_close2;
    private javax.swing.JLabel success;
    // End of variables declaration//GEN-END:variables

//    private void setTime() {
//        new Thread(){
//            public void run(){
//                while(timeRun==0)
//                {
//                    Calendar cal = new GregorianCalendar();
//                    
//                    int hour=cal.get(Calendar.HOUR);
//                    int min=cal.get(Calendar.MINUTE);
//                    int sec=cal.get(Calendar.SECOND);
//                    int am_pm=cal.get(Calendar.AM_PM);
//                    
//                    String DayNight="";
//                    if(am_pm==1){
//                        DayNight="PM";
//                    }
//                    else{
//                        DayNight="AM";
//                    }
//                    String time =hour+":"+min+":"+sec;
//                    String day_night = DayNight;
//                    Clock.setText(time);
//                    Am_Pm.setText(day_night);
//                }
//            }
//        }.start();
//    }

    private void setHide() {
        
       
        
        success.setVisible(false);
        error.setVisible(false);
        IDcheck_ReqForm_panel.setVisible(false);
        EmpId_Form.setVisible(false);
        ID_form.setVisible(false);
        WorkShift_Form.setVisible(false);
        WorkShift_combo_form.setVisible(false);
        contact_form.setVisible(false);
        Contact_txt_form.setVisible(false);
        Reason_form.setVisible(false);
        Reason_area_form_Scroll.setVisible(false);
        Reason_area_form.hide();
        LeaveDate_form.setVisible(false);
        Ldate_form.setVisible(false);
        Duration_form.setVisible(false);
        Duration_combo_form.setVisible(false);
        Email_form.setVisible(false);
        Email_txt_form.setVisible(false);
        Submit_Leave_form.setVisible(false);
        Form_cancel.setVisible(false);
        
        WorkShiftError_noUser.setVisible(false);
        TpNoError_noUser.setVisible(false);
        AddressError_noUser.setVisible(false);
        JoinDateError_noUser.setVisible(false);
        EmailAddressError_noUser.setVisible(false);
        IDError_noUser1.setVisible(false);
        
        
    }

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("SLogo.png")));
    }
}        
    
    
    
    


    

